### ISSUE TITLE
[1.14] Rendered Images cut off

### ISSUE THREAD

**Issue by IronPiston** [CyclopsMC/IconExporter#7] opened 2019-11-25 00:37 UTC
#### Issue type:

- :bug: Bug

____

#### Short description:

After trying to render, the resulting were only the top left.
![Screenshot from 2019-11-24 18-23-50](https://user-images.githubusercontent.com/11603684/69504353-9cda2e00-0ee7-11ea-97f1-26ae6fc8d401.png)

#### Steps to reproduce the problem:

Run /iconexporter export [any scale]

#### Expected behaviour:

The images should be the full sprite/model, not a portion.

____

#### Versions:

- This mod: 1.2.0
- Minecraft: 1.14.4
- Forge: 28.1.92

**Comment by rubensworks** [comment] 2019-11-25 07:21
Weird, it works with any scale for me...

What scale did you use for the screenshot above?

What OS are you using?

**Comment by IronPiston** [comment] 2019-11-25 15:17
Scale for that screenshot was 512, but 32 gave the same problem. 

I'm using Fedora 30 I think, I haven't updated in a while. 

Weirdly, the 1.12 version works fine on the same computer.

**Comment by rubensworks** [comment] 2019-12-29 14:18
I can't reproduce this myself unfortunately (works fine on Mac).
If someone running on Linux would be able to debug this, that'd be great.

**Comment by IronPiston** [comment] 2020-01-13 23:36
So I just tried again, and the issue seems to be gone(I just reinstalled Fedora in the last few days). This seems to have been a problem on my end, since the mod hasn't updated since I posted this issue.

**Comment by rubensworks** [comment] 2020-01-14 07:27
That's good to hear, closing this then.
Should anyone else experience this problem in the future, feel free to comment here.

**Comment by Krutoy242** [comment] 2020-06-05 17:37
1.12.2
First run of `export` command gave right result. But than i tried to enable `general.fileNameHashTag=true`. Now no matter of size i set - everything exported in half.
I already tried to return options to original or reload minecraft - problem still here.

<img src=https://i.imgur.com/2JRRy6F.png>


After some investigation, i found that it somehow connected with MC window size - when i resized window to maximum - problem disapear.

**Comment by rubensworks** [comment] 2020-06-05 17:50
@Krutoy242 What OS are you using?

**Comment by Krutoy242** [comment] 2020-06-05 20:13
> @Krutoy242 What OS are you using?

Windows 10

**Comment by rubensworks** [comment] 2020-06-08 07:09
I'll look into it again in any case, but I'm using Mac, so I'm not able to do any debugging on Windows unfortunately.

**Comment by rubensworks** [comment] 2020-09-11 19:05
I'm unable to reproduce this myself (on Mac) with different resolutions.

I highly suspect this is an OS-specific issue. Since I'm not able to debug this myself, I hope someone else is able to find the problem and suggest a PR.

**Comment by MindGames18** [comment] 2020-10-17 04:02
Hello there  @rubensworks .  I had the same issue in my windows 10. the exported icons were cut off partially. 
and after some time investigating it myself, I ended up finding out that turning the gameto full screen (F11 default for windows) before exporting fixes this issue.  

Maybe you'll be able to reproduce this in mac if you try exporting from windowed mode (speculating) 
thanks! hope this info helps you and others who may stumble here

**Comment by rubensworks** [comment] 2020-10-17 06:50
Note to self: auto-toggle full-screen mode when exporting.

**Comment by Hekera** [comment] 2021-04-10 05:44
I think I've found the source of the issue, at least on Windows. It has to do with the GUI scale option in Minecraft video settings, which I've had on Auto. Changing resolutions/system scale/fullscreen around produces different results because it changes the GUI scale that Minecraft automatically determines. Once I set the GUI scale to a specific number, the results of the icon export remained consistent between resolutions/etc. GUI scale 2 seems to export icons that are the actual scale specified in the command, and that are not cut off.

**Comment by DarkAngel22579** [comment] 2021-04-10 12:35
Chiming in with a 1080p monitor (since Hek's is 1440p). Setting the GUI scale to 2 makes it export at the right scale, regardless of fullscreen/windowed. I normally have GUI set to 3, which caused a 50% increase in the size of the icons. I'd assume GUI scale 1 would cause a 50% decrease, but I haven't tested that.

**Comment by rubensworks** [comment] 2021-04-13 16:05
Thanks for all the input. I've managed to reproduce the problem with different GUI scales.
Fix incoming...

**Closed as completed** 2021-04-13 16:09 UTC
Labels: bug
